### ISSUE TITLE
Canal Slack

### ISSUE THREAD

**Issue by jimmy-collazos** [AdrianClv/solidity-docs-es#28]
En el README se comenta que hay un canal de Slack ¿Podrían decirme cual es el canal?

En caso de tenerlo podríamos añadirlo al Readme.

**Comment by AdrianClv** [comment]
Hola @jimmy-collazos, el slack que estamos usando es el de Ethereum Madrid, un canal privado. Puedes pedir una invitación en https://ethereum-madrid-slack.herokuapp.com/
Luego escríbeme a @adrianclv ahí para que te de acceso al canal.
